# Timeout in seconds that Limine will wait for if no user input is received.
timeout: 0

# The entry name that will be displayed on the boot menu.
/KyroOS Titanium
    protocol: limine
    path: boot():/boot/kernel.elf

    # Userspace Binaries
    module_path: boot():/bin/init
    module_path: boot():/bin/hello
    module_path: boot():/bin/lsblk
    module_path: boot():/bin/wget
    module_path: boot():/bin/game
    module_path: boot():/bin/test
    module_path: boot():/bin/cursor_test
    module_path: boot():/bin/gradient_demo
    module_path: boot():/bin/kpm
    module_path: boot():/bin/installer

    # Configs
    module_path: boot():/boot/limine/limine.conf
