#include "kyroolib.h" // for print, panic equivalent
#include <stddef.h>
#include <stdint.h>
#include <string.h>

// Called when a buffer overflow is detected
void __chk_fail(void) {
  print("__chk_fail: Buffer overflow detected!\n");
  exit(1);
}

// Stubs for string functions with buffer size checking
// These are generated by the compiler when FORTIFY_SOURCE is enabled

char *__strcpy_chk(char *dest, const char *src, size_t dest_len) {
  size_t len = strlen(src);
  if (len >= dest_len) {
    __chk_fail();
  }
  return memcpy(dest, src, len + 1);
}

void *__memcpy_chk(void *dest, const void *src, size_t len, size_t dest_len) {
  if (len > dest_len) {
    __chk_fail();
  }
  return memcpy(dest, src, len);
}

char *__strcat_chk(char *dest, const char *src, size_t dest_len) {
  size_t cur_len = strlen(dest);
  size_t src_len = strlen(src);
  if (cur_len + src_len >= dest_len) {
    __chk_fail();
  }
  return strcat(dest, src);
}

// We might need others like __sprintf_chk, etc. eventually
